import { Geist, Geist_Mono } from "next/font/google";
import Head from "next/head";
import "../assets/css/style.css";
import "../assets/css/color.css";
import "../assets/css/animate.css";
import "../assets/css/flaticon.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "../assets/css/responsive.css";
import "../assets/css/flaticon.css";
import "./globals.css";

// Load fonts using Next.js font optimization
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"], // Subset to use
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"], // Subset to use
});

export const metadata = {
  title: "Buradon Inc",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {/* No need to import fonts here since we're using next/font/google */}
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
          rel="stylesheet"
        />
        <link
          href="https://cdn.jsdelivr.net/gh/flaticon-icons/flaticon-icons@1.0.0/styles.min.css"
          rel="stylesheet"
        />
      </Head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
